### ISSUE TITLE
[FEAT] Harden game-2048 helm chart

### ISSUE THREAD

**Issue by micbegin** [aws-samples/eks-blueprints-actions-workflow#16]
**Is your feature request related to a problem? Please describe.**
Misconfigurations that may lead to security problems are reported by the [Checkov workflow](https://github.com/aws-samples/eks-blueprints-actions-workflow/actions/runs/4399073194).

**Describe the solution you'd like**
- Change the manifests [helm/game-2048/templates](../helm/game-2048/templates) so that Checkov does not report any securit risks.
- Disable Checkov soft fail mode in [.pre-commit-config.yaml](../.pre-commit-config.yaml) and [.github/workflows/checkov.yml](../.github/workflows/checkov.yml).

**Comment by ishwar-amzn** [comment]
Hello @micbegin , I would like to work on this issue, can I start working on this?

**Comment by micbegin** [comment]
Abosultely! Please follow the [contributing guidelines](https://github.com/aws-samples/eks-blueprints-actions-workflow/blob/main/CONTRIBUTING.md) and create a PR so we can review your changes.
