### ISSUE TITLE
[FEAT] Move Karpenter example to subfolder

### ISSUE THREAD

**Issue by micbegin** [aws-samples/eks-blueprints-actions-workflow#21]
**Is your feature request related to a problem? Please describe.**
Only one example exists at the root of the repo. We should move it to plan for adding more examples later.

**Describe the solution you'd like**
Move the terraform files at the root to the karpenter subfolder.

**Comment by ishwar-amzn** [comment]
@micbegin I would like to work on this issue, can I start working on this?

**Comment by micbegin** [comment]
Abosultely! Please follow the [contributing guidelines](https://github.com/aws-samples/eks-blueprints-actions-workflow/blob/main/CONTRIBUTING.md) and create a PR so we can review your changes.
